version: "3.9"
networks:
  dagster_network:
    driver: bridge
    name: podman_network


services:
  ubuntu-podman-dev:
    image: localhost/ubuntu-podman
    stdin_open: true
    tty: true
    user: "ubuntu"
    devices:
      - "/dev/fuse:/dev/fuse"
    security_opt:
      - "label=disable"
    networks:
      - dagster_network
    volumes:
      - ./:/workspace   # Mount current directory to /workspace in container
  ubuntu-podman-ssh:
    image: localhost/ubuntu-podman
    stdin_open: true
    tty: true
    devices:
      - "/dev/fuse:/dev/fuse"
    security_opt:
      - "label=disable"
    networks:
      - dagster_network
    ports:
      - "2222:22"         # Map container SSH port to host
    command: ["/usr/sbin/sshd", "-D"]  # Start SSHD in foreground
