version: "3.9"
networks:
  podman_network:
    driver: bridge
    name: podman_network


services:
  ubuntu-podman-dev:
    image: localhost/ubuntu-podman-2
    stdin_open: true
    tty: true
    user: "ubuntu"
    devices:
      - "/dev/fuse:/dev/fuse"
    security_opt:
      - "label=disable"
    networks:
      - podman_network
    volumes:
      - ./:/workspace   # Mount current directory to /workspace in container
  rocky-podman-ssh:
    image: localhost/rocky-podman-2
    stdin_open: true
    tty: true
    devices:
      - "/dev/fuse:/dev/fuse"
    security_opt:
      - "label=disable"
    networks:
      - podman_network
    ports:
      - "2222:22"         # Map container SSH port to host
